---
- name: Connect to spotify keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886


- name: Set ppa spotify
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    update_cache: yes


- name: Install spotify
  become: true
  become_user: root
  apt:
    name: spotify-client
    state: present

- name: Install pavucontrol
  become: true
  become_user: root
  apt:
    name: pavucontrol
    state: present



## 1. Add the Spotify repository signing key to be able to verify downloaded packages
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
#
## 2. Add the Spotify repository
#echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
#
## 3. Update list of available packages
#sudo apt-get update
#
## 4. Install Spotify
#sudo apt-get install spotify-client
#