---

- name: Install chromium-browser
  become: true
  become_user: root
  apt: name=chromium-browser state=present

- name: install vlc
  become: true
  become_user: root
  apt: name=vlc state=present 


- name: install browser-plugin-vlc
  become: true
  become_user: root
  apt: name=browser-plugin-vlc state=present 


#- name: install i3
#  become: true
#  become_user: root
#  apt: name=i3 state=present 
#
#
#- name: install i3
#  become: true
#  become_user: root
#  apt: name=i3 state=present 
#
#- name: install i3
#  become: true
#  become_user: root
#  apt: name=i3 state=present 
