---
- include_vars: defaults/paths.yml
- include_vars: vault.yml
- include_vars: main.yml

- name: install
  become: true
  become_user: root
  apt: name=mcabber state=present
  register: presence


- name: set config
  template: src=mcabberrc.j2 dest=~/.mcabberrc

- name:
  file:
    path: ~/.mcabber/histo
    mode: 0700
    state: directory
